### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by Liroo** [peauc/peauc.dev#1]
Really don't know why I'm looking this repo but please add 

`node_modules/`

in .gitignore

**Comment by peauc** [comment]
I've added ./node_module/*, wouldn't that work ?

**Comment by Liroo** [comment]
Idk never used this syntax, prefer to use node-modules/

**Comment by Liroo** [comment]
Related PR: #2 
Nice, now you should remove node_modules from your local repo using 
`git rm ...` or `rm ... && git add ...`  and ship it ⛵ 🚀

**Comment by peauc** [comment]
I'll do this asap, thanks for the heads up.
Keeping the issue up until i've fixed it.

**Comment by Liroo** [comment]
👍
